{
  "fixes": [
      "^before/::after/"
  ],
  "codecov": {
    "require_ci_to_pass": true
  },
  "comment": {
    "layout": "reach,diff,flags,files,footer",
    "behavior": "default",
    "require_changes": false
  },
  "parsers": {
    "gcov": {
      "branch_detection": {
        "loop": true,
        "macro": false,
        "method": false,
        "conditional": true
      }
    }
  },
  "coverage": {
    "range": [
        70,
        100
    ],
    "round": "down",
    "precision": 2
  }
}