INSERT INTO CATEGORY (DESCRIPTION) VALUES ('American');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('italian');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Mexican');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('fast food');

INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('pinch');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Each');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Dash');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Pint');